# Merging on indexes

## Video lecture Transcript

**1. Merging on indexes**

So far, we've only looked at merging two tables together using their columns. In this lesson, we'll discuss how to merge tables using their indexes. Often, the DataFrame indexes are given a unique id that we can use when merging two tables together.

**2. Table with an index**

Here, we show the movies table that was introduced earlier in this chapter. The index is the default 0, 1, 2, 3, etc., auto-increment. In this second version, the id column is the index for the table.

**3. Setting an index**

There are different methods to set the index of a table, but if our data starts off in a CSV file, we can use the index_col argument of the read_csv method. This lesson will not focus on how to set a table index, but how to use that index to merge two tables together.

**4. Merge index datasets**

Recall our example to merge the movies and taglines tables using the id column with a left join. Let's recreate that merge using the index which is now the id for tables.

**5. Merging on index**

Our merge statement looks identical to before. However, in this case we are inputting to the 'on' argument the index level name which is called 'id'. The merge method automatically adjusts to accept index names or column names. The returned table looks as before, except the 'id' is the index.

**6. MultiIndex datasets**

Let's try a multiIndex merge. Here, we have two tables with a multiIndex that holds the movie ID and cast ID. The first table, named 'samuel', has the movie and cast ID for a group of movies that Samuel L. Jackson acted in. The second table, named cast, has the movie ID and cast ID for a number of movie characters. Let's merge these two tables on their multiIndex.

**7. MultiIndex merge**

In this merge, we pass in a list of index level names to the 'on' argument, just like we did when merging on multiple columns. Since this is an inner join, both the movie_id and cast_id must match in each table to be returned in the result. It's interesting to see that Samuel Jackson has acted in over 65 movies! That's a lot.

**8. Index merge with left_on and right_on**

There is one more thing regarding merging on indexes. If the index level names are different between the two tables that we want to merge, then we can use the left_on and right_on arguments of the merge method. Let's go back to our movies table, shown in the top panel, and merge it with our movies_to_genres table, shown in the lower panel.

**9. Index merge with left_on and right_on**

In this merge, since we list the movies table as the left table, we set left_on equal to id and right_on equal to movie_id. Additionally, since we are merging on indexes, we need to set left_index and right_index to True. These arguments take only True or False. Whenever we are using the left_on or right_on arguments with an index, we need to set the respective left_index and right_index arguments to True. The left_index and right_index tell the merge method to use the separate indexes.

**10. Let's practice!**

Now it's time for you try out a few exercises.

## Exercise 1:
Index merge for movie ratings
To practice merging on indexes, you will merge `movies` and a table called `ratings` that holds info about movie ratings. Ensure that your merge returns all rows from the `movies` table, and only matching rows from the `ratings` table.

The `movies` and `ratings` tables have been loaded for you.

___

### Instructions:
Merge the `movies` and `ratings` tables on the `id` column, *keeping all rows from the movies table* (Self note: this means a left merge), and save the result as `movies_ratings`.

### Code:
```python
# Merge to the movies table the ratings table on the index
movies_ratings = movies.merge(ratings, on="id", how="left")

# Print the first few rows of movies_ratings
print(movies_ratings.head())


# Shell output

                      title  popularity release_date  vote_average  vote_count
id                                                                            
257            Oliver Twist      20.416   2005-09-23           6.7       274.0
14290  Better Luck Tomorrow       3.877   2002-01-12           6.5        27.0
38365             Grown Ups      38.864   2010-06-24           6.0      1705.0
9672               Infamous       3.681   2006-11-16           6.4        60.0
12819       Alpha and Omega      12.301   2010-09-17           5.3       124.0
```
___


## Exercise 1 Recap:
Good work! Merging on indexes is just like merging on columns, so if you need to merge based on indexes, there's no need to turn the indexes into columns first.
___

## Exercise 2:
Do sequels earn more?
It is time to put together many of the aspects that you have learned in this chapter. In this exercise, you'll find out which movie sequels earned the most compared to the original movie. To answer this question, you will merge a modified version of the `sequels` and `financials` tables where their index is the movie ID. You will need to choose a merge type that will return all of the rows from the `sequels` table and not all the rows of `financials` table need to be included in the result. From there, you will join the resulting table to itself so that you can compare the revenue values of the original movie to the sequel. Next, you will calculate the difference between the two revenues and sort the resulting dataset.

The `sequels` and `financials` tables have been provided.

___

### Instructions 1:
With the `sequels` table on the left, merge to it the `financials` table on index named `id`, ensuring that all the rows from the `sequels` are returned and some rows from the other table may not be returned, Save the results to `sequels_fin`.

### Code 1:
```python
# Merge sequels and financials on index id
sequels_fin = sequels.merge(financials, on="id", how="left")
```
___

### Instructions 2:
Merge the `sequels_fin` table to itself with an inner join, where the left and right tables merge on `sequel` and `id` respectively with suffixes equal to `('_org','_seq')`, saving to `orig_seq`.

### Code 2:
```python
# Merge sequels and financials on index id
sequels_fin = sequels.merge(financials, on='id', how='left')

# Self merge with suffixes as inner join with left on sequel and right on id
orig_seq = sequels_fin.merge(sequels_fin,
                            how='inner',
                            left_on='sequel', 
                            right_on='id', right_index=True,
                            suffixes=['_org','_seq'])

# Add calculation to subtract revenue_org from revenue_seq 
orig_seq['diff'] = orig_seq['revenue_seq'] - orig_seq['revenue_org']
```
___

### Instructions 3:
Select the `title_org`, `title_seq`, and `diff` columns of `orig_seq` and save this as `titles_diff`.

### Code 3:
```python
# Merge sequels and financials on index id
sequels_fin = sequels.merge(financials, on='id', how='left')

# Self merge with suffixes as inner join with left on sequel and right on id
orig_seq = sequels_fin.merge(sequels_fin, 
                            how='inner', 
                            left_on='sequel', 
                            right_on='id',
                            right_index=True,
                            suffixes=('_org','_seq'))

# Add calculation to subtract revenue_org from revenue_seq 
orig_seq['diff'] = orig_seq['revenue_seq'] - orig_seq['revenue_org']

# Select the title_org, title_seq, and diff 
titles_diff = orig_seq[['title_org', 'title_seq', 'diff']]
```
___

### Instructions 4:
Sort by `titles_diff` by `diff` in descending order and print the first few rows.

### Code 4:
```python
# Merge sequels and financials on index id
sequels_fin = sequels.merge(financials, on='id', how='left')

# Self merge with suffixes as inner join with left on sequel and right on id
orig_seq = sequels_fin.merge(sequels_fin, how='inner', left_on='sequel', 
                             right_on='id', right_index=True,
                             suffixes=('_org','_seq'))

# Add calculation to subtract revenue_org from revenue_seq 
orig_seq['diff'] = orig_seq['revenue_seq'] - orig_seq['revenue_org']

# Select the title_org, title_seq, and diff 
titles_diff = orig_seq[['title_org','title_seq','diff']]

# Print the first rows of the sorted titles_diff
print(titles_diff.sort_values('diff', ascending=False).head())

# Shell output
               title_org        title_seq       diff
id                                                  
331    Jurassic Park III   Jurassic World  1.145e+09
272        Batman Begins  The Dark Knight  6.303e+08
10138         Iron Man 2       Iron Man 3  5.915e+08
863          Toy Story 2      Toy Story 3  5.696e+08
10764  Quantum of Solace          Skyfall  5.225e+08
```


## Exercise 1 Recap:
Amazing, that was great work! To complete this exercise, you needed to merge tables on their index and merge another table to itself. After the calculations were added and sub-select specific columns, the data was sorted. You found out that Jurassic World had one of the highest of all, improvement in revenue compared to the original movie.
___